import random


def speed_fun():
    SPEED_X = random.randint(-1, 1)
    SPEED_Y = random.randint(-1, 1)

    if SPEED_X == 0 or SPEED_Y == 0:
        SPEED_X, SPEED_Y = speed_fun()
    
    return SPEED_X, SPEED_Y


BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

SCREEN_HEIGHT = 480
SCREEN_WIDTH = SCREEN_HEIGHT*2  # 640

BOLL_WIDTH = 30
BOLL_HEIGTH = 30

CHAR_WIDTH = 10
CHAR_HEIGTH = 120

BOLL_POS_X = SCREEN_WIDTH // 2 - BOLL_WIDTH // 2
BOLL_POS_Y = SCREEN_HEIGHT // 2 - BOLL_HEIGTH // 2

PLAYER_POS_X = 10
PLAYER_POS_Y = SCREEN_HEIGHT // 2 - CHAR_HEIGTH // 2

ADVS_POS_X = SCREEN_WIDTH - 10 - CHAR_WIDTH 
ADVS_POS_Y = SCREEN_HEIGHT // 2 - CHAR_HEIGTH // 2

SPEED_X, SPEED_Y = speed_fun()

PLAYER_SPEED = 10
ADVS_SPEED = SPEED_Y - 10

PLAYER_POINTERS = 0
ADVS_POINTERS = 0

DASH_LENGTH = 10

ACER = 6

FPS = 30
